defmodule Portfolio.Projects do

  @doc """
  List of projects.
  """
  def list_projects do
    [
      %{
        title: "Agents",
        description: "Full Stack Q&A application for audio rooms, featuring room creation, question submission, and audio-to-text transcription using Google Gemini.",
        technologies: ["Vite", "TypeScript", "Fastify", "Google Gemini", "Docker", "PostgreSQL", "TailwindCSS"],
        image: "https://raw.githubusercontent.com/ricardoof/agents/main/web/public/home.png",
        link_deploy: "https://agents-lake-omega.vercel.app/",
        link_github: "https://github.com/ricardoof/agents"
      },
      %{
        title: "DevStage",
        description: "Full Stack event application featuring registration, rankings, and invitations.",
        technologies: ["Next", "TypeScript", "TailwindCSS", "PostgreSQL", "Fastify", "Redis"],
        image: "https://raw.githubusercontent.com/ricardoof/devstage/main/web/public/home.png",
        link_deploy: "https://devstage-ten.vercel.app/",
        link_github: "https://github.com/ricardoof/devstage"
      },
      %{
        title: "In.orbit",
        description: "Full Stack application for managing daily goals, with features to create, track progress, and view a weekly summary.",
        technologies: ["Vite", "TypeScript", "TailwindCSS", "Docker", "PostgreSQL", "Zod", "Fastify"],
        image: "https://raw.githubusercontent.com/ricardoof/inorbit/main/web/public/home.png",
        link_deploy: "",
        link_github: "https://github.com/ricardoof/inorbit"
      },
      %{
        title: "InstaBytes",
        description: "Simple Full Stack social media application featuring post creation and display, with photo descriptions generated by Google Gemini.",
        technologies: ["HTML", "CSS", "JavaScript", "Node", "MongoDB", "Google Gemini"],
        image: "https://raw.githubusercontent.com/ricardoof/instabytes/main/web/assets/images/home.png",
        link_deploy: "",
        link_github: "https://github.com/ricardoof/instabytes"
      },
      %{
        title: "Casa Verde",
        description: "Landing page for a plant store with an API for sending emails.",
        technologies: ["Vite", "CSS", "JavaScript"],
        image: "https://raw.githubusercontent.com/ricardoof/casa-verde/main/public/images/casa-verde.png",
        link_deploy: "https://casa-verde-delta-topaz.vercel.app/",
        link_github: "https://github.com/ricardoof/casa-verde"
      },
      %{
        title: "Jogos indies brasileiros",
        description: "Web application that searches for Brazilian games within a list.",
        technologies: ["HTML", "CSS", "JavaScript"],
        image: "https://raw.githubusercontent.com/ricardoof/jogos-indies-br/main/imagens/home.png",
        link_deploy: "https://jogos-indies-br.vercel.app/",
        link_github: "https://github.com/ricardoof/jogos-indies-br"
      },
      %{
        title: "Filmes populares",
        description: "Web application that consumes The Movie Database (TMDB) API to display, search, and favorite movies, fully responsive for desktop and mobile.",
        technologies: ["HTML", "CSS", "JavaScript"],
        image: "https://raw.githubusercontent.com/ricardoof/movie-db-api/main/src/image/filmes-populares-desktop.png",
        link_deploy: "https://movie-db-api-xi.vercel.app/",
        link_github: "https://github.com/ricardoof/movie-db-api"
      },
      %{
        title: "Netflix",
        description: "Netflix landing page clone, fully responsive for desktop and mobile.",
        technologies: ["HTML", "CSS"],
        image: "https://raw.githubusercontent.com/ricardoof/netflix/main/img/netflix-desktop.png",
        link_deploy: "https://netflix-nine-blush.vercel.app/",
        link_github: "https://github.com/ricardoof/netflix"
      },
      %{
        title: "Spotify",
        description: "Spotify landing page clone, fully responsive for desktop and mobile, including artist search from a JSON file.",
        technologies: ["HTML", "CSS", "JavaScript"],
        image: "https://raw.githubusercontent.com/ricardoof/spotify-clone/main/src/assets/images/spotify-desktop.png",
        link_deploy: "https://spotify-clone-chi-eight.vercel.app/",
        link_github: "https://github.com/ricardoof/spotify-clone"
      }
    ]
  end
end
